version: '3.7'
services:
  mysql-container:
    image: mysql:8.0
    ports:
      - '3300:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass